src/cursos/urls.py
from django.urls import path
from . import views

app_name = "cursos"
urlpatterns = [

    path('', views.adcourse_list_view, name='adcourse_list'),
    path('curso/crear/', views.adcourse_create_view, name='adcourse_create'),
    path('curso/editar/<int:id>/', views.adcourse_edit_view, name='adcourse_edit'),
    path('curso/<int:id>/miembros/', views.adcourse_members_view, name='adcourse_members'),
    path('curso/<int:id>/agregar-miembros/', views.adcourse_addmember_view, name='adcourse_add_members'),
    path('curso/<int:id>/agregando-miembro/<int:user_id>/', views.adcourse_addingmember_view, name='adcourse_adding_member'),
    path('curso/<int:id>/remover-miembro/<int:user_id>/', views.adcourse_members_remove_view, name='adcourse_removing_member'),
    path('curso/<int:id>/eliminar/', views.course_delete_view, name='adcourse_delete'),

    path('curso/<int:id>/add-members/', views.adcourse_addmember_view, name='adcourse_addmember'),
    path('curso/<int:id>/salir/', views.course_leave_view, name='course_quit'),


    path('menu/', views.menu, name='menu'),
    path('like/<int:id>/', views.like_curso, name='course_like'),
    path('read/<int:id>/', views.read_lecture, name='course_read_lecture'),
    path('watch/<int:id>/', views.watch_video, name='course_watch_video'),
    path('curso/<int:id>/', views.course_detail_view, name='course_detail'),

    # Modulos
    path('curso/agregar-modulo/<int:id>/', views.course_create_module_view, name='course_create_module'),
    path('curso/editar-modulo/<int:id>/', views.course_edit_module_view, name='course_edit_module'),


    path('curso/agregar-actividad/<int:id>/<int:action>/', views.course_create_item_view, name='course_create_item'),
    path('curso/editar-actividad/<int:id>/<int:action>/', views.course_edit_item_view, name='course_edit_item'),


    # Lecturas
    path('curso/lectura/<int:id>/', views.course_lecture_view, name='course_lecture'),
    path("curso/lectura/<int:id>/eliminar/", views.course_lecture_delete_view, name='course_lecture_delete'),


    # Actividades
    path('curso/actividad/<int:id>/', views.course_activity_view, name='course_activity'),
    path('curso/actividad/<int:id>/eliminar', views.course_activity_delete_view, name='course_activity_delete'),
    path('curso/entrega/<int:id>/', views.course_activity_entry_detail_view, name='course_activity_entry'),
    path('curso/entrega/<int:id>/archivo/', views.course_activity_entry_file_view, name='course_activity_entry_file'),
    path('curso/entrega/<int:id>/eliminar/', views.course_activity_entry_delete_view, name='course_activity_entry_delete'),


    # Videos
    path('curso/video/<int:id>/', views.course_video_view, name='course_video'),
    path('curso/video/<int:id>/eliminar/', views.course_video_delete_view, name='course_video_delete'),


    # Resource
    path('curso/recurso/<int:id>/', views.course_resource_view, name='course_resource'),
    path('curso/recurso/<int:id>/eliminar/', views.course_resource_delete_view, name='course_resource_delete'),
    path('curso/recurso/<int:id>/archivo/', views.course_resource_download_view, name='course_resource_file'),
    

    # Hangman
    path('curso/hangman/<int:id>/', views.course_hangman_view, name='course_hangman'),
    path('curso/hangman/<int:id>/eliminar/', views.course_hangman_delete_view, name='course_hangman_delete'),
    path('curso/hangman/<int:id>/crear-opcion/', views.course_hangman_option_create_view, name='course_hangman_add_option'),
    path('curso/hangman/<int:id>/editar-opcion/', views.course_hangman_option_edit_view, name='course_hangman_edit_option'),
    path('curso/hangman/<int:id>/eliminar-opcion/', views.course_hangman_option_delete_view, name='course_hangman_delete_option'),
    path('curso/hangman/<int:id>/play/', views.course_hangman_answer_view, name='course_hangman_play'),
    path('curso/hangman/<int:id>/complete/', views.course_hangman_complete_view, name='course_hangman_complete'),


    # Sopa
    path('curso/sopa/<int:id>/', views.course_sopa_view, name='course_sopa'),
    path('curso/sopa/<int:id>/eliminar/', views.course_sopa_delete_view, name='course_sopa_delete'),
    path('curso/sopa/<int:id>/crear-opcion/', views.course_sopa_option_create_view, name='course_sopa_add_option'),
    path('curso/sopa/<int:id>/editar-opcion/', views.course_sopa_option_edit_view, name='course_sopa_edit_option'),
    path('curso/sopa/<int:id>/eliminar-opcion/', views.course_sopa_option_delete_view, name='course_sopa_delete_option'),
    path('curso/sopa/<int:id>/play/', views.course_sopa_complete_view, name='course_sopa_complete'),

    # Puzzle
    path('curso/puzzle/<int:id>/', views.course_puzzle_view, name='course_puzzle'),
    path('curso/puzzle/<int:id>/eliminar/', views.course_puzzle_delete_view, name='course_puzzle_delete'),
    path('curso/puzzle/<int:id>/play/', views.course_puzzle_complete_view, name='course_puzzle_complete'),

    # Quiz
    path('curso/quiz/<int:id>/', views.course_quiz_view, name='course_quiz'),
    path('curso/quiz/<int:id>/eliminar/', views.course_quiz_delete_view, name='course_quiz_delete'),
    path('curso/quiz/<int:id>/answer/', views.course_quiz_answer_view, name='course_quiz_answer'),
    path('curso/quiz/<int:id>/answered/', views.course_quiz_answered_view, name='course_quiz_answered'),
    path('curso/quiz/<int:id>/submit/<int:calif>/', views.course_quiz_submit_view, name='course_quiz_submit'),
    path('curso/quiz/<int:id>/agregar-pregunta/', views.course_quiz_create_question_view, name='course_quiz_add_question'),
    path('curso/quiz/<int:id>/editar-pregunta/', views.course_quiz_update_question_view, name='course_quiz_edit_question'),
    path('curso/quiz/<int:id>/eliminar-pregunta/', views.course_quiz_delete_question_view, name='course_quiz_delete_question'),
    path('curso/quiz/<int:id>/agregar-opcion/', views.course_quiz_option_create_view, name='curso_question_add_option'),
    path('curso/quiz/<int:id>/editar-opcion/', views.course_quiz_option_update_view, name='curso_question_edit_option'),
    path('curso/quiz/<int:id>/eliminar-opcion/', views.course_quiz_option_delete_view, name='curso_question_delete_option'),
    path('curso/quiz/calificar/<int:user_pk>/<int:quiz_pk>/<int:grade>/', views.course_quiz_grade, name='curso_quiz_grade'),


]

src/iepam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('panel/', views.panel, name='panel'),
    path('cursos/', include(('cursos.urls'), namespace='cursos')),
    path('miembros/', include(('users.urls'), namespace='miembros')),

    path('my-404/',views.my404_view, name='404'),
    path('my-403/',views.my403_view, name='403'),
    path('my-500/',views.my500_view, name='500')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_DIR)

src/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [

    path('login/', views.user_login_view, name='login'),
    path('logout/', views.user_logout_view, name='logout'),


    path('', views.aduser_list_view, name='users_list'),
    
    # Admin views
    path('register/', views.aduser_member_register_View, name='user_create'),
    path('user-detail/<int:id>/', views.aduser_detail_view, name='user_detail'),
    path('user-detail/<int:id>/cv/', views.user_get_cv_view, name='user_cv'),
    path('user-detail/<int:id>/cv/descargar/', views.user_download_cv_view, name='user_cv_download'),
    path('user-detail/<int:id>/update/', views.aduser_update_view, name='user_update'),
    path('user-detail/<int:id>/update/cv/', views.aduser_change_cv, name='user_update_cv'),
    path('user-detail/<int:id>/update/profile-pic/', views.aduser_change_profilepic_view, name='user_update_profilepic'),
    path('user-detail/<int:id>/update/cambiar-grupo/', views.aduser_change_group, name='user_change_group'),

    path('user-detail/<int:id>/deactivate/', views.aduser_deactivate_view, name='user_deactivate'),
    path('user-detail/<int:id>/activate/', views.aduser_activate_view, name='user_activate'),

    # Profile views
    path('profile/', views.memuser_profile_view, name='user_profile'),
    path('profile/update/', views.memuser_update_view, name='user_profile_update'),
    path('profile/update/cv/', views.memuser_changeCV_view, name='user_profile_updateCV'),
    path('profile/update/profile-pic/', views.memuser_change_profilepic_view, name='user_profile_updatepic'),
]

src/templates/admin.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<title>Admin</title>

{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/admin.css' %}">

<div id="id-app" style="display: none;">admin</div>

<div class="container-window">
    <div class="admin-title">Panel de administración</div>

    <div class="admin-container">
    
        <div class="admin-list">
            <div class="admin-list-title">Administrar Usuarios</div>

            <hr class="hr-nice">
            <div class="admin-list-header">
                <form class="admin-list-search-container">
                    <input class="admin-list-search" placeholder="Buscar..." id="usuario" name="usuario">
                    <span class="material-icons admin-list-search-icon">search</span>
                </form>
                <a href="{% url 'miembros:user_create' %}" class="admin-btn-register tooltip">
                    <span class="material-icons">add</span>
                    <div class="tooltiptext">Registrar nuevo usuario</div>
                </a>

            </div>
            {% for user in users %}
            <a href="{% url 'users:user_detail' id=user.pk %}">
                <div class="admin-list-item">
                    <div class="admin-list-item-title">{{ user.get_full_name }}</div>
                </div>
            </a>
            {% endfor %}

        </div>
    
        <div class="admin-list">
            <div class="admin-list-title">Administrar Capacitaciones</div>
            <hr class="hr-nice">

            <div class="admin-list-header">
                <form class="admin-list-search-container">
                    <input class="admin-list-search" placeholder="Buscar..." id="courses" name="courses">
                    <span class="material-icons admin-list-search-icon">search</span>
                </form>
                <a href="{% url 'cursos:adcourse_create' %}" class="admin-btn-register tooltip">
                    <span class="material-icons">add</span>
                    <div class="tooltiptext">Registrar nueva capacitación</div>
                </a>

            </div>

            {% for course in courses %}
            <a href="{% url 'cursos:course_detail' id=course.pk %}">
                <div class="admin-list-item">
                    <div class="admin-list-item-title">{{ course.name }}</div>
                </div>
            </a>
            {% endfor %}

        </div>
    </div>
    
</div>

{% endblock %}

src/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!-- Social media icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/side-panel.css' %}">

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <link rel="icon" type="svg" href="{% static 'svg/iepam-logo-white.svg' %}">
    {% block head %} {% endblock %}
</head>
<body>
    <nav class="navbar-back">
        <div class="navbar-container">
            <a href="/" class="navbar-title"><img src="{% static 'svg/iepam-logo-white.svg' %}"><p>IEPAM</p></a>
            <div class="navbar-items">
                <ul>
                    <il id="Inicio" class="list active">
                        <a id="InicioA" href="{% url 'index' %}"><span class="material-icons">home</span><p>Inicio</p></a>
                    </il>
                    <il id="Capacitaciones" class="list">
                        <a id="CapacitacionesA" href="{% url 'cursos:menu' %}"><span class="material-icons">class</span><p>Capacitaciones</p></a>
                    </il>
                    <il id="Perfil" class="list">
                        <a id="PerfilA" href="{% url 'miembros:user_profile' %}"><span class="material-icons">account_circle</span><p>Perfil</p></a>
                    </il>

                    {% if perms.users.is_admin %}
                    <il id="Admin" class="list">
                        <a id="AdminA" href="{% url 'panel' %}"><span class="material-icons">admin_panel_settings</span><p>Admin Panel</p></a>
                    </il>
                    {% else %}
                    <il id="Admin" class="list" style="visibility: hidden;">
                        <a id="AdminA" href=""><span class="material-icons">admin_panel_settings</span><p>Admin Panel</p></a>
                    </il>
                    {% endif %}

                    <div id="navbar-item-01" class="navbar-item-bg"></div>
                    <div id="navbar-item-02" class="navbar-item-of"></div>


                    <il id="Logout" class="nav-end">
                        <a href="{% url 'users:logout' %}"><span class="material-icons">logout</span><p>Logout</p></a>
                    </il>
                </ul>
            </div>
            
        </div>
        
    </nav>
    <main>
        <div class="container">
            <!-- Block for main content of child templates -->
            {% block body %} {% endblock %}
        </div>

        <script src="{% static 'js/nav.js' %}"></script>
    </main>
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<title>Inicio</title>

{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">

<div id="id-app" style="display: none;">main</div>

<div class="container-window">
    <div class="index-main-container">

        <div class="index-header">
            <div class="index-title">Bienvenido de vuelta, {{ user.first_name }}.
                <div class="index-subtitle">¡Vas bien, sigue así!</div>
            </div>
            <div class="index-date">
                {% if date.weekday == 0 %}
                Lunes,
                {% elif date.weekday == 1 %}
                Martes,
                {% elif date.weekday == 2 %}
                Miercoles,
                {% elif date.weekday == 3 %}
                Jueves,
                {% elif date.weekday == 4 %}
                Viernes,
                {% elif date.weekday == 5 %}
                Sabado,
                {% elif date.weekday == 6 %}
                Domingo,
                {% endif %} 
                {{ date.day }} de 
                {% if date.month == 1 %}
                Enero
                {% elif date.month == 2 %}
                Febrero
                {% elif date.month == 3 %}
                Marzo
                {% elif date.month == 4 %}
                Abril
                {% elif date.month == 5 %}
                Mayo
                {% elif date.month == 6 %}
                Junio
                {% elif date.month == 7 %}
                Julio
                {% elif date.month == 8 %}
                Agosto
                {% elif date.month == 9 %}
                Septiembre
                {% elif date.month == 10 %}
                Octubre
                {% elif date.month == 11 %}
                Noviembre
                {% elif date.month == 12 %}
                Diciembre
                {% endif %}
                {{ date.year }}
            </div>
        </div>

        <div class="index-secondary-container">
            
            <div>
                <!-- Estadisiticas -->
                <div class="index-section-container">

                    <div class="index-section-title">Estadísticas</div>
                    <div class="index-section-body">
                        <div class="statistics-card">
                            <div class="statistics-card-number">{{ cap_actuales }}</div>
                            <div class="statistics-card-text">Capacitaciones en curso</div>
                        </div>
                        <div class="statistics-card">
                            <div class="statistics-card-number">{{ cap_cursadas }}</div>
                            <div class="statistics-card-text">Capacitaciones completadas</div>
                        </div>
                        <div class="statistics-card">
                            <div class="statistics-card-number">{{ act_completadas }}</div>
                            <div class="statistics-card-text">Actividades realizadas</div>
                        </div>
                        <div class="statistics-card">
                            <div class="statistics-card-number">{{ cap_creadas }}</div>
                            <div class="statistics-card-text">Capacitaciones creadas</div>
                        </div>
                    </div>

                </div>
                <!-- Estadisiticas end -->
                <br>
                <!-- Progreso -->
                <div class="index-section-container">

                    <div class="index-section-title">Tu progreso</div>
                    <div class="index-section-body">
                        <div class="progress-container">

                            {% for course in courses_percentages %}

                                <div class="progress-item">
                                    <div class="progress-name">
                                        {{ course.0 }}
                                    </div>
                                    <div class="progress-bar">
                                        <div class="progress-bar-bar">
                                            <div id="bar{{forloop.counter}}" class="progress-bar-fill"></div>
                                        </div>
                                        <p>{{ course.1 }}%</p>
                                    </div>
                                </div>

                                {% if not forloop.last %}
                                    <div class="progress-separator"></div>
                                {% endif %}

                                <script>
                                    document.getElementById('bar{{forloop.counter}}').style.transform = 'scaleX(0)'
                                    document.getElementById('bar{{forloop.counter}}').style.transform = 'scaleX({{course.2}})'
                                </script>
                            {% empty %}
                                <div class="progress-item">
                                    <div class="progress-name">
                                        No estás cursando ninguna capacitación
                                    </div>
                                    <div class="progress-bar">
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                </div>
                <!-- Progreso end -->
                <br>
                <!-- Continuar Cursos -->
                <div class="index-section-container">

                    <div class="index-section-title">Continúa capacitandote</div>
                    <div class="index-section-body">
                        <div class="continue-container">

                            {% for curso in continue_cursos %}
                                <a class="no-style-a" href="{% url 'cursos:course_detail' id=curso.0.pk %}">
                                    <div class="continue-curso">
                                        <div class="continue-curso-img">
                                            {% if curso.0.bg_image %}
                                                <img src="{{ curso.0.bg_image.url }}">
                                            {% else %}
                                                <img src="{% static 'img/view.jpg' %}">
                                            {% endif %}
                                        </div>
                                        <div class="continue-text">
                                            <div class="continue-curso-title">
                                                {{ curso.0.name }}
                                            </div>
                                            <div class="continue-curso-continuar">
                                                <p>Continua</p>
                                                <span class="material-icons">east</span>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            {% empty %}
                            <a class="no-style-a" href="{% url 'cursos:menu' %}">
                                <div class="continue-curso">
                                    <div class="continue-curso-img">
                                        <img src="{% static 'img/view.jpg' %}">
                                    </div>
                                    <div class="continue-text">
                                        <div class="continue-curso-title">
                                            No estás inscrito en ninguna capacitación
                                        </div>
                                        <div class="continue-curso-continuar">
                                            <p>Capacitate</p>
                                            <span class="material-icons">east</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                            {% endfor %}

                        </div>
                    </div>

                </div>
                <!-- Continuar Cursos end -->


            </div>

        </div>

    </div>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js" integrity="sha512-QSkVNOCYLtj73J4hbmVoOV6KVZuMluZlioC+trLpewV8qMjsWqlIQvkn1KGX2StWvPMdWGBqim1xlC8krl1EKQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

{% endblock %}