src/cursos/urls.py
from django.urls import path
from . import views

app_name = "cursos"
urlpatterns = [

    path('', views.adcourse_list_view, name='adcourse_list'),
    path('curso/crear/', views.adcourse_create_view, name='adcourse_create'),
    path('curso/editar/<int:id>/', views.adcourse_edit_view, name='adcourse_edit'),
    path('curso/<int:id>/miembros/', views.adcourse_members_view, name='adcourse_members'),
    path('curso/<int:id>/agregar-miembros/', views.adcourse_addmember_view, name='adcourse_add_members'),
    path('curso/<int:id>/agregando-miembro/<int:user_id>/', views.adcourse_addingmember_view, name='adcourse_adding_member'),
    path('curso/<int:id>/remover-miembro/<int:user_id>/', views.adcourse_members_remove_view, name='adcourse_removing_member'),
    path('curso/<int:id>/eliminar/', views.course_delete_view, name='adcourse_delete'),

    path('curso/<int:id>/add-members/', views.adcourse_addmember_view, name='adcourse_addmember'),
    path('curso/<int:id>/salir/', views.course_leave_view, name='course_quit'),


    path('menu/', views.menu, name='menu'),
    path('like/<int:id>/', views.like_curso, name='course_like'),
    path('read/<int:id>/', views.read_lecture, name='course_read_lecture'),
    path('watch/<int:id>/', views.watch_video, name='course_watch_video'),
    path('curso/<int:id>/', views.course_detail_view, name='course_detail'),

    # Modulos
    path('curso/agregar-modulo/<int:id>/', views.course_create_module_view, name='course_create_module'),
    path('curso/editar-modulo/<int:id>/', views.course_edit_module_view, name='course_edit_module'),


    path('curso/agregar-actividad/<int:id>/<int:action>/', views.course_create_item_view, name='course_create_item'),
    path('curso/editar-actividad/<int:id>/<int:action>/', views.course_edit_item_view, name='course_edit_item'),


    # Lecturas
    path('curso/lectura/<int:id>/', views.course_lecture_view, name='course_lecture'),
    path("curso/lectura/<int:id>/eliminar/", views.course_lecture_delete_view, name='course_lecture_delete'),


    # Actividades
    path('curso/actividad/<int:id>/', views.course_activity_view, name='course_activity'),
    path('curso/actividad/<int:id>/eliminar', views.course_activity_delete_view, name='course_activity_delete'),
    path('curso/entrega/<int:id>/', views.course_activity_entry_detail_view, name='course_activity_entry'),
    path('curso/entrega/<int:id>/archivo/', views.course_activity_entry_file_view, name='course_activity_entry_file'),
    path('curso/entrega/<int:id>/eliminar/', views.course_activity_entry_delete_view, name='course_activity_entry_delete'),


    # Videos
    path('curso/video/<int:id>/', views.course_video_view, name='course_video'),
    path('curso/video/<int:id>/eliminar/', views.course_video_delete_view, name='course_video_delete'),


    # Resource
    path('curso/recurso/<int:id>/', views.course_resource_view, name='course_resource'),
    path('curso/recurso/<int:id>/eliminar/', views.course_resource_delete_view, name='course_resource_delete'),
    path('curso/recurso/<int:id>/archivo/', views.course_resource_download_view, name='course_resource_file'),
    

    # Hangman
    path('curso/hangman/<int:id>/', views.course_hangman_view, name='course_hangman'),
    path('curso/hangman/<int:id>/eliminar/', views.course_hangman_delete_view, name='course_hangman_delete'),
    path('curso/hangman/<int:id>/crear-opcion/', views.course_hangman_option_create_view, name='course_hangman_add_option'),
    path('curso/hangman/<int:id>/editar-opcion/', views.course_hangman_option_edit_view, name='course_hangman_edit_option'),
    path('curso/hangman/<int:id>/eliminar-opcion/', views.course_hangman_option_delete_view, name='course_hangman_delete_option'),
    path('curso/hangman/<int:id>/play/', views.course_hangman_answer_view, name='course_hangman_play'),
    path('curso/hangman/<int:id>/complete/', views.course_hangman_complete_view, name='course_hangman_complete'),


    # Sopa
    path('curso/sopa/<int:id>/', views.course_sopa_view, name='course_sopa'),
    path('curso/sopa/<int:id>/eliminar/', views.course_sopa_delete_view, name='course_sopa_delete'),
    path('curso/sopa/<int:id>/crear-opcion/', views.course_sopa_option_create_view, name='course_sopa_add_option'),
    path('curso/sopa/<int:id>/editar-opcion/', views.course_sopa_option_edit_view, name='course_sopa_edit_option'),
    path('curso/sopa/<int:id>/eliminar-opcion/', views.course_sopa_option_delete_view, name='course_sopa_delete_option'),
    path('curso/sopa/<int:id>/play/', views.course_sopa_complete_view, name='course_sopa_complete'),

    # Puzzle
    path('curso/puzzle/<int:id>/', views.course_puzzle_view, name='course_puzzle'),
    path('curso/puzzle/<int:id>/eliminar/', views.course_puzzle_delete_view, name='course_puzzle_delete'),
    path('curso/puzzle/<int:id>/play/', views.course_puzzle_complete_view, name='course_puzzle_complete'),

    # Quiz
    path('curso/quiz/<int:id>/', views.course_quiz_view, name='course_quiz'),
    path('curso/quiz/<int:id>/eliminar/', views.course_quiz_delete_view, name='course_quiz_delete'),
    path('curso/quiz/<int:id>/answer/', views.course_quiz_answer_view, name='course_quiz_answer'),
    path('curso/quiz/<int:id>/answered/', views.course_quiz_answered_view, name='course_quiz_answered'),
    path('curso/quiz/<int:id>/submit/<int:calif>/', views.course_quiz_submit_view, name='course_quiz_submit'),
    path('curso/quiz/<int:id>/agregar-pregunta/', views.course_quiz_create_question_view, name='course_quiz_add_question'),
    path('curso/quiz/<int:id>/editar-pregunta/', views.course_quiz_update_question_view, name='course_quiz_edit_question'),
    path('curso/quiz/<int:id>/eliminar-pregunta/', views.course_quiz_delete_question_view, name='course_quiz_delete_question'),
    path('curso/quiz/<int:id>/agregar-opcion/', views.course_quiz_option_create_view, name='curso_question_add_option'),
    path('curso/quiz/<int:id>/editar-opcion/', views.course_quiz_option_update_view, name='curso_question_edit_option'),
    path('curso/quiz/<int:id>/eliminar-opcion/', views.course_quiz_option_delete_view, name='curso_question_delete_option'),
    path('curso/quiz/calificar/<int:user_pk>/<int:quiz_pk>/<int:grade>/', views.course_quiz_grade, name='curso_quiz_grade'),


]

src/iepam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('panel/', views.panel, name='panel'),
    path('cursos/', include(('cursos.urls'), namespace='cursos')),
    path('miembros/', include(('users.urls'), namespace='miembros')),

    path('my-404/',views.my404_view, name='404'),
    path('my-403/',views.my403_view, name='403'),
    path('my-500/',views.my500_view, name='500')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_DIR)

src/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [

    path('login/', views.user_login_view, name='login'),
    path('logout/', views.user_logout_view, name='logout'),


    path('', views.aduser_list_view, name='users_list'),
    
    # Admin views
    path('register/', views.aduser_member_register_View, name='user_create'),
    path('user-detail/<int:id>/', views.aduser_detail_view, name='user_detail'),
    path('user-detail/<int:id>/cv/', views.user_get_cv_view, name='user_cv'),
    path('user-detail/<int:id>/cv/descargar/', views.user_download_cv_view, name='user_cv_download'),
    path('user-detail/<int:id>/update/', views.aduser_update_view, name='user_update'),
    path('user-detail/<int:id>/update/cv/', views.aduser_change_cv, name='user_update_cv'),
    path('user-detail/<int:id>/update/profile-pic/', views.aduser_change_profilepic_view, name='user_update_profilepic'),
    path('user-detail/<int:id>/update/cambiar-grupo/', views.aduser_change_group, name='user_change_group'),

    path('user-detail/<int:id>/deactivate/', views.aduser_deactivate_view, name='user_deactivate'),
    path('user-detail/<int:id>/activate/', views.aduser_activate_view, name='user_activate'),

    # Profile views
    path('profile/', views.memuser_profile_view, name='user_profile'),
    path('profile/update/', views.memuser_update_view, name='user_profile_update'),
    path('profile/update/cv/', views.memuser_changeCV_view, name='user_profile_updateCV'),
    path('profile/update/profile-pic/', views.memuser_change_profilepic_view, name='user_profile_updatepic'),
]

src/cursos/forms.py
from django import forms

from .models import Course, Modulo, Lectura, Actividad, PuzzleGame, Question, Quiz, SopaGame, SopaOption, Video, QuestionOption, FileResource, HangmanGame, HangmanOption
from django.core.validators import MaxLengthValidator, FileExtensionValidator, MinLengthValidator


CV_MAX_SIZE = 1024 * 1024 * 5
# CV_MAX_SIZE = 5

def file_max_size(max_size: int):
    def helper(value):
        if value.size > max_size:
            raise forms.ValidationError('Archivo excede limite de espacio')
    return helper

PERMITTED_FILE_EXTENSIONS = [
    'pdf', 'docx', 'xlsx', 'pptx'
]

class CourseCreateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'description', 'bg_image']
        widgets = {
            'description': forms.Textarea()
        }
        validators = {
            'description': MaxLengthValidator(255),
            'bg_image': file_max_size(CV_MAX_SIZE)
        }

class ModuleAddForm(forms.ModelForm):
    class Meta:
        model = Modulo
        fields = ['name']

class LectureAddForm(forms.ModelForm):
    class Meta:
        model = Lectura
        fields = ['name', 'description', 'content', 'author']
        widgets = {
            'content': forms.Textarea()
        }
        validators = {
            'content': MaxLengthValidator(2024)
        }

class ActivityAddForm(forms.ModelForm):
    class Meta:
        model = Actividad
        fields = ['name', 'description', 'instructions']
        widgets = {
            'description': forms.Textarea()
        }
        validators = {
            'description': MaxLengthValidator(500)
        }


class EntregaAddForm(forms.Form):
    file = forms.FileField(validators=[FileExtensionValidator(allowed_extensions=PERMITTED_FILE_EXTENSIONS)])


class VideoAddForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['name', 'description', 'url']
        widgets = {
            'description': forms.Textarea()
        }
        validators = {
            'description': MaxLengthValidator(500)
        }

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['name', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5})
        }
        validators = {
            'description': MaxLengthValidator(500)
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['prompt',]

        widgets = {
            'prompt': forms.Textarea(attrs={'rows': 5})
        }



class QuestionOptionsForm(forms.ModelForm):
    correct = forms.BooleanField(required=False)
    is_updating = False
    class Meta:
        model = QuestionOption
        fields = ['prompt', 'correct']

        widgets = {
            'prompt': forms.Textarea(attrs={'rows': 5})
        }

    def clean(self):
        all_cleaned_data = super().clean()
        question = self.instance.question
        correct = all_cleaned_data['correct']


        if len(QuestionOption.objects.filter(question=question)) >= 5 and not self.is_updating:
            raise forms.ValidationError('Solo puede haber un maximo de 5 preguntas')


        if correct:
            if QuestionOption.objects.filter(question=question).exists():
                options = question.options.all()
                if QuestionOption.objects.filter(pk=self.instance.pk).exists():
                    options = options.exclude(pk=self.instance.pk)


                for option in options:
                    if option.correct:
                        raise forms.ValidationError('¡Ya existe una respuesta correcta!')


class FileResourceForm(forms.ModelForm):
    class Meta:
        model = FileResource
        fields = ('title', 'description', 'resource')

        widgets = {
            'description': forms.Textarea(attrs={'rows': 3})
        }

class HangmanForm(forms.ModelForm):
    class Meta:
        model = HangmanGame
        fields = ('title', 'description')

        widgets = {
            'description': forms.Textarea(attrs={'rows':3})
        }

class HangmanOptionForm(forms.ModelForm):
    is_updating = False
    class Meta:
        model = HangmanOption
        fields = ('option', 'hint_1', 'hint_2')


    def clean(self):
        all_cleaned_data = super().clean()
        hangman = self.instance.game

        if len(HangmanOption.objects.filter(game=hangman)) >= 5 and not self.is_updating:
            raise forms.ValidationError('No pueden existir mas de 5 opciones')


    
    def clean_hint_1(self):
        hint_1 = self.cleaned_data['hint_1']

        hint_1 = hint_1.strip().split(' ')[0]
        return hint_1

    def clean_hint_2(self):
        hint_2 = self.cleaned_data['hint_2']

        hint_2 = hint_2.strip().split(' ')[0]
        return hint_2


class SopaForm(forms.ModelForm):
    class Meta:
        model = SopaGame
        fields = ('title', 'description')

        widgets = {
            'description': forms.Textarea(attrs={'rows':3})
        }

class SopaOptionForm(forms.ModelForm):
    is_updating = False
    class Meta:
        model = SopaOption
        fields = ('option',)


    def clean(self):
        all_cleaned_data = super().clean()
        game = self.instance.game

        if len(SopaOption.objects.filter(game=game)) >= 5 and not self.is_updating:
            raise forms.ValidationError('No se pueden tener mas de 5 opciones')

class PuzzleForm(forms.ModelForm):
    class Meta:
        model = PuzzleGame
        fields = ('title', 'description')

        widgets = {
            'description': forms.Textarea(attrs={'rows':3})
        }

src/cursos/templates/cursos/admin/course_add_member.html
{% extends 'base.html' %}

{% block body %}



<h1>{{ course.name }}</h1>
<hr>


{% for member in members %}


    <h3><a href="{% url 'users:user_detail' id=member.user.pk %}">{{ member.get_full_name }}</a></h3>
    <a href="{% url 'cursos:adcourse_adding_member' id=course.pk user_id=member.user.pk %}">Add</a>


{% empty %}
    <h3>No Users found</h3>

{% endfor %}
{% endblock %}

src/cursos/templates/cursos/admin/course_create_form.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Social media icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- CSS -->    
    <link rel="stylesheet" href="{% static 'css/register.css' %}">

    <title>Crear Capacitación</title>
    <link rel="icon" type="svg" href="{% static 'svg/iepam-logo-white.svg' %}">
</head>
<body>
    
    <main>
        <div class="container">
            <a class="title"><img src="{% static 'svg/iepam-logo-white.svg' %}"><p>IEPAM</p></a>
            <div class="register-container">
                <div class="register-title">Crear capacitación</div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="input-line">
                        <label for="">Nombre</label>
                        <div>
                            {{ form.name.errors }}
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="input-line">
                        <label for="">Descripción</label>
                        <div>
                            {{ form.description.errors }}
                            {{ form.description }}
                        </div>
                    </div>

                    <div>
                        <label for="">Imagen</label>
                        <div>
                            {{ form.bg_image.erros }}
                            {{ form.bg_image }}
                        </div>
                    </div>
                    <a href="{% url 'cursos:menu' %}" class="btn-cancel margin-right-btn">Cancelar</a>
                    <button class="btn-register" type="submit">Crear</button>
                </form>
            </div>
        </div>
    </main>
</body>
</html>

src/cursos/templates/cursos/admin/course_delete.html
{% extends 'base.html' %}

{% block body %}


    <h4>Eliminar {{ course.name }}</h4>
    <form method="post">
        {% csrf_token %}

        <button>Eliminar</button>

    </form>

{% endblock %}

src/cursos/templates/cursos/admin/course_edit_form.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Social media icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- CSS -->    
    <link rel="stylesheet" href="{% static 'css/register.css' %}">

    <title>Editar Capacitación</title>
    <link rel="icon" type="svg" href="{% static 'svg/iepam-logo-white.svg' %}">
</head>
<body>
    
    <main>
        <div class="container">
            <a class="title"><img src="{% static 'svg/iepam-logo-white.svg' %}"><p>IEPAM</p></a>
            <div class="register-container">
                <div class="register-title">Editar capacitación</div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="input-line">
                        <label for="">Nombre</label>
                        <div>
                            {{ form.name.errors }}
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="input-line">
                        <label for="">Descripción</label>
                        <div>
                            {{ form.description.errors }}
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="input-line">
                        <label for="">Imagen</label>
                        <div>
                            {{ form.bg_image.errors }}
                            {{ form.bg_image }}
                        </div>
                    </div>
                    <a href="{% url 'cursos:course_detail' id=course.pk %}" class="btn-cancel margin-right-btn">Cancelar</a>
                    <button class="btn-register" type="submit">Guardar</button>
                </form>
            </div>
        </div>
    </main>
</body>
</html>

src/cursos/templates/cursos/admin/course_members.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<title>Miembros</title>

{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/course.css' %}">

<div id="id-app" style="display: none;">cap</div>

<div class="container-window">
    <a href="{% url 'cursos:course_detail' id=course.pk %}" class="no-style-a">
        <div class="return">
            <span class="material-icons">chevron_left</span>
            Volver a la capacitación
        </div>
    </a>
    <div class="course-title">Miembros</div>
    <div class="course-author">{{ course.name }}</div>
    <div class="members-container">
        <div class="member-cell">
            <!-- <a href="{% url 'cursos:adcourse_add_members' id=course.pk %}">Agregar miembro</a> -->
            <!-- ! NOTE -->
            <!-- ! MembersOf model use here -->
            <h2>Miembros actuales ({{ members.count }})</h2>
            {% for member in members %}

            <div class="member">
                {% if perms.users.is_admin %}
                    <a class="member-name" href="{% url 'users:user_detail' id=member.member.user.pk %}">{{ member.member.get_full_name }}</a>
                    <a class="delete-member tooltip" href="{% url 'cursos:adcourse_removing_member' id=course.pk user_id=member.member.user.pk %}">
                        <span class="material-icons">close</span>
                        <div class="tooltiptext">Desinscribir</div>
                    </a>
                {% else %}
                    <a class="member-name" href="">{{ member.member.get_full_name }}</a>
                {% endif %}
            </div>   

            {% empty %}

                <h3>No members</h3>

            {% endfor %}
        </div>
    
        {% if perms.users.is_admin %}
            <div class="member-cell">

                <h2>Agregar miembros</h2>
        
                <form method="get">
                    <div class="search-container">
                        <div>
                            <input type="text" class="searchbar" placeholder="Buscar..." name="nombre" id="nombre">
                            <span class="material-icons searchbar-icon">search</span>
                        </div>
                        <button class="search-button" type="submit">
                            Buscar
                        </button>
                    </div>
                </form>
                <!-- ! ExtendedUser model use here -->
                {% for member in not_members %}
                <div class="member">
                    <a class="member-name" href="{% url 'users:user_detail' id=member.user.pk %}">{{ member.get_full_name }}</a>
                    <a class="add-member tooltip" href="{% url 'cursos:adcourse_adding_member' id=course.pk user_id=member.user.pk %}">
                        <span class="material-icons">add</span>
                        <div class="tooltiptext">Inscribir</div>
                    </a>
                </div>
                {% empty %}

                {% endfor %}
    
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}

src/cursos/templates/cursos/admin/course_remove_member.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Social media icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- CSS -->    
    <link rel="stylesheet" href="{% static 'css/register.css' %}">

    <title>Remover Usuario</title>
    <link rel="icon" type="svg" href="{% static 'svg/iepam-logo-white.svg' %}">
</head>
<body>
    
    <main>
        <div class="container">
            <a class="title"><img src="{% static 'svg/iepam-logo-white.svg' %}"><p>IEPAM</p></a>
            <div class="register-container  confirm-container">
                <div class="register-subtitle">Remover usuario</div>
                <p>Al remover al usuario eliminaras todo su progreso y documentos del cursos</p>
                <br>
                <form method="post">
                    {% csrf_token %}
                    <div class="btn-container-vertical">
                        <button class="red-color" type="submit">Eliminar</button>
                        <a class="btn-cancel" href="{% url 'cursos:adcourse_members' id=course.pk %}">Cancelar</a>
                    </div>
                </form>

            </div>
        </div>
    </main>
</body>
</html>

src/cursos/templates/cursos/admin/courses_list.html
{% extends 'base.html' %}

{% block body %}

{% endblock %}