src/cursos/urls.py
from django.urls import path
from . import views

app_name = "cursos"
urlpatterns = [

    path('', views.adcourse_list_view, name='adcourse_list'),
    path('curso/crear/', views.adcourse_create_view, name='adcourse_create'),
    path('curso/editar/<int:id>/', views.adcourse_edit_view, name='adcourse_edit'),
    path('curso/<int:id>/miembros/', views.adcourse_members_view, name='adcourse_members'),
    path('curso/<int:id>/agregar-miembros/', views.adcourse_addmember_view, name='adcourse_add_members'),
    path('curso/<int:id>/agregando-miembro/<int:user_id>/', views.adcourse_addingmember_view, name='adcourse_adding_member'),
    path('curso/<int:id>/remover-miembro/<int:user_id>/', views.adcourse_members_remove_view, name='adcourse_removing_member'),
    path('curso/<int:id>/eliminar/', views.course_delete_view, name='adcourse_delete'),

    path('curso/<int:id>/add-members/', views.adcourse_addmember_view, name='adcourse_addmember'),
    path('curso/<int:id>/salir/', views.course_leave_view, name='course_quit'),


    path('menu/', views.menu, name='menu'),
    path('like/<int:id>/', views.like_curso, name='course_like'),
    path('read/<int:id>/', views.read_lecture, name='course_read_lecture'),
    path('watch/<int:id>/', views.watch_video, name='course_watch_video'),
    path('curso/<int:id>/', views.course_detail_view, name='course_detail'),

    # Modulos
    path('curso/agregar-modulo/<int:id>/', views.course_create_module_view, name='course_create_module'),
    path('curso/editar-modulo/<int:id>/', views.course_edit_module_view, name='course_edit_module'),


    path('curso/agregar-actividad/<int:id>/<int:action>/', views.course_create_item_view, name='course_create_item'),
    path('curso/editar-actividad/<int:id>/<int:action>/', views.course_edit_item_view, name='course_edit_item'),


    # Lecturas
    path('curso/lectura/<int:id>/', views.course_lecture_view, name='course_lecture'),
    path("curso/lectura/<int:id>/eliminar/", views.course_lecture_delete_view, name='course_lecture_delete'),


    # Actividades
    path('curso/actividad/<int:id>/', views.course_activity_view, name='course_activity'),
    path('curso/actividad/<int:id>/eliminar', views.course_activity_delete_view, name='course_activity_delete'),
    path('curso/entrega/<int:id>/', views.course_activity_entry_detail_view, name='course_activity_entry'),
    path('curso/entrega/<int:id>/archivo/', views.course_activity_entry_file_view, name='course_activity_entry_file'),
    path('curso/entrega/<int:id>/eliminar/', views.course_activity_entry_delete_view, name='course_activity_entry_delete'),


    # Videos
    path('curso/video/<int:id>/', views.course_video_view, name='course_video'),
    path('curso/video/<int:id>/eliminar/', views.course_video_delete_view, name='course_video_delete'),


    # Resource
    path('curso/recurso/<int:id>/', views.course_resource_view, name='course_resource'),
    path('curso/recurso/<int:id>/eliminar/', views.course_resource_delete_view, name='course_resource_delete'),
    path('curso/recurso/<int:id>/archivo/', views.course_resource_download_view, name='course_resource_file'),
    

    # Hangman
    path('curso/hangman/<int:id>/', views.course_hangman_view, name='course_hangman'),
    path('curso/hangman/<int:id>/eliminar/', views.course_hangman_delete_view, name='course_hangman_delete'),
    path('curso/hangman/<int:id>/crear-opcion/', views.course_hangman_option_create_view, name='course_hangman_add_option'),
    path('curso/hangman/<int:id>/editar-opcion/', views.course_hangman_option_edit_view, name='course_hangman_edit_option'),
    path('curso/hangman/<int:id>/eliminar-opcion/', views.course_hangman_option_delete_view, name='course_hangman_delete_option'),
    path('curso/hangman/<int:id>/play/', views.course_hangman_answer_view, name='course_hangman_play'),
    path('curso/hangman/<int:id>/complete/', views.course_hangman_complete_view, name='course_hangman_complete'),


    # Sopa
    path('curso/sopa/<int:id>/', views.course_sopa_view, name='course_sopa'),
    path('curso/sopa/<int:id>/eliminar/', views.course_sopa_delete_view, name='course_sopa_delete'),
    path('curso/sopa/<int:id>/crear-opcion/', views.course_sopa_option_create_view, name='course_sopa_add_option'),
    path('curso/sopa/<int:id>/editar-opcion/', views.course_sopa_option_edit_view, name='course_sopa_edit_option'),
    path('curso/sopa/<int:id>/eliminar-opcion/', views.course_sopa_option_delete_view, name='course_sopa_delete_option'),
    path('curso/sopa/<int:id>/play/', views.course_sopa_complete_view, name='course_sopa_complete'),

    # Puzzle
    path('curso/puzzle/<int:id>/', views.course_puzzle_view, name='course_puzzle'),
    path('curso/puzzle/<int:id>/eliminar/', views.course_puzzle_delete_view, name='course_puzzle_delete'),
    path('curso/puzzle/<int:id>/play/', views.course_puzzle_complete_view, name='course_puzzle_complete'),

    # Quiz
    path('curso/quiz/<int:id>/', views.course_quiz_view, name='course_quiz'),
    path('curso/quiz/<int:id>/eliminar/', views.course_quiz_delete_view, name='course_quiz_delete'),
    path('curso/quiz/<int:id>/answer/', views.course_quiz_answer_view, name='course_quiz_answer'),
    path('curso/quiz/<int:id>/answered/', views.course_quiz_answered_view, name='course_quiz_answered'),
    path('curso/quiz/<int:id>/submit/<int:calif>/', views.course_quiz_submit_view, name='course_quiz_submit'),
    path('curso/quiz/<int:id>/agregar-pregunta/', views.course_quiz_create_question_view, name='course_quiz_add_question'),
    path('curso/quiz/<int:id>/editar-pregunta/', views.course_quiz_update_question_view, name='course_quiz_edit_question'),
    path('curso/quiz/<int:id>/eliminar-pregunta/', views.course_quiz_delete_question_view, name='course_quiz_delete_question'),
    path('curso/quiz/<int:id>/agregar-opcion/', views.course_quiz_option_create_view, name='curso_question_add_option'),
    path('curso/quiz/<int:id>/editar-opcion/', views.course_quiz_option_update_view, name='curso_question_edit_option'),
    path('curso/quiz/<int:id>/eliminar-opcion/', views.course_quiz_option_delete_view, name='curso_question_delete_option'),
    path('curso/quiz/calificar/<int:user_pk>/<int:quiz_pk>/<int:grade>/', views.course_quiz_grade, name='curso_quiz_grade'),


]

src/iepam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('panel/', views.panel, name='panel'),
    path('cursos/', include(('cursos.urls'), namespace='cursos')),
    path('miembros/', include(('users.urls'), namespace='miembros')),

    path('my-404/',views.my404_view, name='404'),
    path('my-403/',views.my403_view, name='403'),
    path('my-500/',views.my500_view, name='500')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_DIR)

src/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [

    path('login/', views.user_login_view, name='login'),
    path('logout/', views.user_logout_view, name='logout'),


    path('', views.aduser_list_view, name='users_list'),
    
    # Admin views
    path('register/', views.aduser_member_register_View, name='user_create'),
    path('user-detail/<int:id>/', views.aduser_detail_view, name='user_detail'),
    path('user-detail/<int:id>/cv/', views.user_get_cv_view, name='user_cv'),
    path('user-detail/<int:id>/cv/descargar/', views.user_download_cv_view, name='user_cv_download'),
    path('user-detail/<int:id>/update/', views.aduser_update_view, name='user_update'),
    path('user-detail/<int:id>/update/cv/', views.aduser_change_cv, name='user_update_cv'),
    path('user-detail/<int:id>/update/profile-pic/', views.aduser_change_profilepic_view, name='user_update_profilepic'),
    path('user-detail/<int:id>/update/cambiar-grupo/', views.aduser_change_group, name='user_change_group'),

    path('user-detail/<int:id>/deactivate/', views.aduser_deactivate_view, name='user_deactivate'),
    path('user-detail/<int:id>/activate/', views.aduser_activate_view, name='user_activate'),

    # Profile views
    path('profile/', views.memuser_profile_view, name='user_profile'),
    path('profile/update/', views.memuser_update_view, name='user_profile_update'),
    path('profile/update/cv/', views.memuser_changeCV_view, name='user_profile_updateCV'),
    path('profile/update/profile-pic/', views.memuser_change_profilepic_view, name='user_profile_updatepic'),
]

src/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from PIL import Image

from pathlib import Path
import os

def cv_upload_handler(instance, filename):
    destination = Path('cv')

    extension = str(Path(filename).suffix)
    file = Path(instance.user.username + extension)

    destination = str(destination / file)
    return destination

def profile_pic_upload_handler(instance, filename):
    destination = Path('profile_pics')

    extension = str(Path(filename).suffix)
    file = Path(instance.user.username + extension)

    destination = str(destination / file)
    return destination


def file_extension_validator(value):
    extension = os.path.splitext(value.name)[1]
    
    if not extension.lower() in ['.pdf',]:
        raise ValidationError('Solo se aceptan valores')


# Create your models here.
class ExtendedUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='extended_user')
    second_last_name = models.CharField('Second LastName',max_length=255)
    birthdate = models.DateField("date")
    academic_level = models.CharField('academic Level', max_length=255)
    profile_pic = models.ImageField('profile_pic', upload_to=profile_pic_upload_handler, blank=True, null=True)
    cv = models.FileField('CV', upload_to=cv_upload_handler, blank=True, null=True, validators=[file_extension_validator,])
    can_teach = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Extended User'
        verbose_name_plural = 'Extended Users'

        permissions = [
            ('is_admin', 'Is admin'),
            ('is_teacher', 'Is Teacher'),
            ('is_student', 'Is Student')
        ]

    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        

        if self.profile_pic:
            img = Image.open(self.profile_pic.path)
            if img.height > 170 or img.width > 170:
                dimensions = (170, 170)
                img.thumbnail(dimensions)
                img.save(self.profile_pic.path)

    
    def __str__(self):
        return str(self.user.username)

    
    def get_full_name(self):
        return f'{self.user.first_name} {self.user.last_name} {self.second_last_name}'

src/users/forms.py
from inspect import Attribute
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group

from datetime import date
from calendar import monthrange

from .models import ExtendedUser
import os

MONTHS = [
    (1, "Enero"), (2, "Febrero"), (3, "Marzo"), (4, "Abril"),
    (5, "Mayo"), (6, "Junio"), (7, "Julio"), (8, "Agosto"),
    (9, "Septiembre"), (10, "Octubre"), (11, "Noviembre"), (12, "Diciembre")
]


USER_TYPES = [
    ('', '----------'),
    ('Administradores', 'Administrador'),
    ('Capacitadores', 'Capacitador'),
    ('Estudiantes', 'Estudiante')
]

User = get_user_model()

CV_MAX_SIZE = 1024 * 1024 * 5
# CV_MAX_SIZE = 5

def file_max_size(max_size: int):
    def helper(value):
        if value.size > max_size:
            raise forms.ValidationError('Archivo excede limite de espacio')
    return helper

def validate_file_extension(value):
    import os
    from django.core.exceptions import ValidationError
    extension = os.path.splitext(value.name)[1]
    valid_extensions = ['.pdf',]
    if not extension.lower() in valid_extensions:
        raise ValidationError('Solo se aceptan archivos pdf')


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=255, min_length=6)
    first_name = forms.CharField(max_length=255)
    first_last_name = forms.CharField(max_length=255)
    second_last_name = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    user_type = forms.ChoiceField(choices=USER_TYPES)

    day = forms.IntegerField(max_value=31, min_value=1, initial=date.today().day, widget=forms.Select(choices=[(num, num) for num in range(1, 32)]))
    month = forms.IntegerField(max_value=12, min_value=1, initial=MONTHS[date.today().month-1], widget=forms.Select(choices=MONTHS))
    year = forms.IntegerField(min_value=1900, max_value=date.today().year, initial=date.today().year, widget=forms.Select(choices=[(year, year) for year in range(1900, date.today().year+1)]))

    academic_level = forms.CharField(max_length=255)
    password = forms.CharField(max_length=300, widget=forms.PasswordInput(attrs={'class':'password-input'}))
    v_password = forms.CharField(max_length=300, widget=forms.PasswordInput(attrs={'class':'password-input'}))
    cv = forms.FileField(required=False, validators=[
                                                        file_max_size(CV_MAX_SIZE), validate_file_extension],
                                                        widget=forms.FileInput(attrs={'class':'custom-file-input', 'id':'file'}))
    profile_pic = forms.ImageField(required=False, 
                                                        widget=forms.FileInput(attrs={'class':'custom-file-input', 'id':'file'}))
    


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self):
        all_clean_data = super().clean()

        # Username uniqueness
        username = all_clean_data['username']

        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Usuario ya esta registrado')

        # Password validation
        password = all_clean_data['password']
        v_password = all_clean_data['v_password']

        if password != v_password:
            raise forms.ValidationError('¡Los Passwords no coinciden!')


        # Validate Email is unique
        email = all_clean_data['email']

        email_exists = User.objects.filter(email=email).exists()
        if email_exists:
            raise forms.ValidationError('Este correo ya esta registrado.')


        # Birth Date Validation
        day = int(all_clean_data['day'])
        month = int(all_clean_data['month'])
        year = int(all_clean_data['year'])

        _, days = monthrange(year, month)

        if day > days:
            raise forms.ValidationError('No es una fecha Valida!')


        user_type = all_clean_data['user_type']
        if user_type == '':
            raise forms.ValidationError('Por favor escoger un un tipo de usuario')

        if not Group.objects.filter(name=user_type).exists():
            raise forms.ValidationError('Ese no es un grupo valido')



class UserUpdateForm(forms.Form):
    first_name = forms.CharField(max_length=255)
    first_last_name = forms.CharField(max_length=255)
    second_last_name = forms.CharField(max_length=255)

    day = forms.IntegerField(max_value=31, min_value=1, widget=forms.Select(
                                                                            choices=[(num, num) for num in range(1, 32)]
                                                                        ))
    month = forms.IntegerField(max_value=12, min_value=1, widget=forms.Select(choices=MONTHS))
    year = forms.IntegerField(min_value=1900, max_value=date.today().year, widget=forms.Select(
                                                                            choices=[(year, year) for year in range(1900, date.today().year+1)]
                                                                        ))

    academic_level = forms.CharField(max_length=255)
    profile_pic = forms.ImageField(required=False, 
                                                widget=forms.FileInput(attrs={'class':'custom-file-input', 'id':'file'}))


    def clean(self):
        all_clean_data = super().clean()

        day = int(all_clean_data['day'])
        month = int(all_clean_data['month'])
        year = int(all_clean_data['year'])

        _, days = monthrange(year, month)

        if days < day:
            raise forms.ValidationError('No es una fecha valida')


class UserCVForm(forms.ModelForm):
    cv = forms.FileField(validators=[file_max_size(CV_MAX_SIZE), validate_file_extension])
    class Meta:
        model = ExtendedUser
        fields = ('cv',)


class ProfilePicForm(forms.ModelForm):
    profile_pic = forms.ImageField(validators=[file_max_size(CV_MAX_SIZE)])
    class Meta:
        model = ExtendedUser
        fields = ('profile_pic',)


class UserChangeGroupForm(forms.Form):
    user_type = forms.ChoiceField(choices=USER_TYPES)

    def clean(self):
        all_cleaned_data = super().clean()

        user_type = all_cleaned_data['user_type']
        if user_type == '':
            raise forms.ValidationError('Por favor escoger un un tipo de usuario')

        if not Group.objects.filter(name=user_type).exists():
            raise forms.ValidationError('Ese no es un grupo valido')

src/users/templates/users/_user_own_courses_snippet.html
<!-- ! Usa el courses  -->
{% for course in courses %}
<a href="{% url 'cursos:course_detail' id=course.pk %}">

    <div class="user-course-card">
        <div class="user-course-card-title">{{ course.name }}</div>
        <div class="user-course-card-desc">{{ course.description }}</div>
        <small>Creado: {{ course.date_created }}</small>
    </div>
</a>
{% empty %}
<h5>Ningun curso</h5>
{% endfor %}

src/users/templates/users/user_cv_form.html
{% extends 'base.html' %}


{% block body %}


    <h1>Change cv</h1>
    <hr>


    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <label for="">Archivo</label>
        <div>
            {{ form.cv.errors }}
            {{ form.cv }}

        </div>



        {% if profile_view %}
            <a href="{% url 'users:user_profile' %}">Cancel</a>
        {% else %}
            <a href="{% url 'users:user_detail' id=extended_user.user.pk %}">Cancel</a>
        {% endif %}
        <button>Actualizar</button>
    </form>

{% endblock %}

src/users/templates/users/user_deactivate.html
{% extends 'base.html' %}


{% block head %}
    <title>{{ extended_user.get_full_name }}</title>
{% endblock %}


{% block body %}

    <h3>¿Deseas desactivar la cuenta de {{extended_user.get_full_name}}</h3>
    <p>
        El miembro ya no podra acceder a su cuenta ni realizar ninguna funcion en la plataforma.
        <br>
        Sin embargo todas sus actividades podran ser auditadas
    </p>
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'users:user_detail' id=extended_user.user.pk %}">Cancel</a>
        <button type="submit">Desactivar</button>
    </form>

{% endblock %}

src/users/templates/users/user_detail.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<title>{{ extended_user.get_full_name }}</title>

{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">

<div id="id-app" style="display: none;">admin</div>

<div class="container-window">
    <div class="profile-rows">

        <div class="profile-rows-cell">
            <a href="{% url 'panel' %}" class="no-style-a" style="position:absolute;">
                <div class="admin-return">
                    <span class="material-icons">chevron_left</span>
                    Volver al panel
                </div>
            </a>

            <div class="profile-background"></div>
            <div class="profile-picture">
                {% if extended_user.profile_pic %}
                    <img src="{{ extended_user.profile_pic.url }}">
                {% else %}
                    <img style="width: 130px; transform: translateX(30px);" src="{% static 'svg/iepam-logo-white.svg' %}">
                {% endif %}
            </div>
            <div class="profile-name">
                <p class="profile-main-name">{{ extended_user.get_full_name }}</p>
                <p class="profile-secondary-name">
                    {% if extended_user.is_admin %}
                        Admin
                    {% elif extended_user.can_teach %}
                        Capacitador
                    {% else %}
                        Usuario
                    {% endif %}
                </p>
            </div>
            
            <a href="{% url 'users:user_change_group' id=extended_user.user.pk %}" class="user-edit-info-third">Cambiar Tipo de usuario</a>

            <a href="{% url 'users:user_update' id=extended_user.user.pk %}" class="user-edit-info-secondary">Editar Perfil</a>
        </div>

        
        <div class="profile-rows-cell">
            <div class="user-cards-container">
                <div class="user-info-container">
                    <p class="user-info-title">Información del usuario</p>
                    <hr class="hr-nice">
                    <div class="user-info-field-container">
                        <p class="user-info-prompt">Nombre Completo</p>
                        <input class="user-info-field" readonly=true value="{{ extended_user.get_full_name }}">
                    </div>
                    <div class="user-info-field-container">
                        <p class="user-info-prompt">Correo electrónico</p>
                        <input class="user-info-field" readonly=true value="{{ extended_user.user.email }}">
                    </div>
                    <div class="user-info-field-container">
                        <p class="user-info-prompt">Fecha de Nacimiento</p>
                        <input class="user-info-field" readonly=true value="{{ extended_user.birthdate }}">
                    </div>
                    <div class="user-info-field-container">
                        <p class="user-info-prompt">Nivel Académico</p>
                        <input class="user-info-field" readonly=true value="{{ extended_user.academic_level }}">
                    </div>
                    <div class="user-info-field-container" style="text-align: center; margin-top: 2rem; margin-bottom: 0.6rem;">

                        {% if extended_user.cv %}
                        <a class="user-info-cv" href="{% url 'users:user_cv' id=extended_user.user.pk %}" target="_blank">Ver CV&nbsp;<span class="material-icons">file_download</span></a>
                        <a class="user-info-cv" href="{% url 'users:user_cv_download' id=user.pk %}">Descargar CV&nbsp;<span class="material-icons">file_download</span></a>
                        {% else %}
                        <a class="user-info-cv" href="{% url 'users:user_update_cv' id=extended_user.user.pk %}">Agregar CV&nbsp;<span class="material-icons">file_download</span></a>
                        <!-- <input type="file" class="user-info-field" readonly=true value="Preparatoria"> -->
                        {% endif %}
                    </div>
                    <br>
                </div>
            
                {% if own_courses %}
                <div class="user-current-courses-container">
                    <p class="user-info-title">Capacitaciones Impartidas</p>
                    <hr class="hr-nice">
            
                {% include 'users/_user_own_courses_snippet.html' with courses=own_courses %}
            
                    <br>
                </div>
            {% endif %}


                <div class="user-current-courses-container">
                    <p class="user-info-title">Capacitaciones actuales</p>
                    <hr class="hr-nice">

                    {% include 'users/_user_courses_snippet.html' with courses=incomplete_courses %}

                    <br>
                </div>
            
                <div class="user-current-courses-container">
                    <p class="user-info-title">Capacitaciones Completadas</p>
                    <hr class="hr-nice">
            
                        {% include 'users/_user_courses_snippet.html' with courses=completed_courses %}
            
                    <br>
                </div>
            </div>
        </div>

    </div>
    
</div>

{% endblock %}

src/users/templates/users/user_profile.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<title>Mi Perfil</title>

{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">

<div id="id-app" style="display: none;">profile</div>

<div class="container-window">
    <div class="profile-rows">

        <div class="profile-rows-cell">
            <div class="profile-background"></div>
            <div class="profile-picture">
                {% if user.extended_user.profile_pic %}
                    <img src="{{ user.extended_user.profile_pic.url }}">
                {% else %}
                    <img src="{% static 'img/view.jpg' %}">
                {% endif %}
            </div>
            <div class="profile-name">
                <p class="profile-main-name">{{ user.extended_user.get_full_name }}</p>
                <p class="profile-secondary-name">
                    {% if user.extended_user.is_admin %}
                        Admin
                    {% elif user.extended_user.can_teach %}
                        Capacitador
                    {% else %}
                        Usuario
                    {% endif %}
                </p>
            </div>
        </div>
        <a href="{% url 'users:user_profile_update' %}" class="user-edit-info-secondary">Editar Perfil</a>
        <div class="profile-rows-cell">
            <div class="user-cards-container">
                <div class="user-info-container">
                    <p class="user-info-title">Información del usuario</p>
                    <hr class="hr-nice">
                    <div class="user-info-field-container">
                        <p class="user-info-prompt">Nombre Completo</p>
                        <input class="user-info-field" readonly=true value="{{ user.extended_user.get_full_name }}">
                    </div>
                    <div class="user-info-field-container">
                        <p class="user-info-prompt">Correo electrónico</p>
                        <input class="user-info-field" readonly=true value="{{ user.email }}">
                    </div>
                    <div class="user-info-field-container">
                        <p class="user-info-prompt">Fecha de Nacimiento</p>
                        <input class="user-info-field" readonly=true value="{{ user.extended_user.birthdate }}">
                    </div>
                    <div class="user-info-field-container">
                        <p class="user-info-prompt">Nivel Académico</p>
                        <input class="user-info-field" readonly=true value="{{ user.extended_user.academic_level }}">
                    </div>
                    <div class="user-info-field-container" style="text-align: center; margin-top: 2rem; margin-bottom: 0.6rem;">
                        {% if user.extended_user.cv %}

                        <a class="user-info-cv" href="{% url 'users:user_cv' id=user.pk %}">Ver CV&nbsp;<span class="material-icons">file_download</span></a>
                        <a class="user-info-cv" href="{% url 'users:user_cv_download' id=user.pk %}">Descargar CV&nbsp;<span class="material-icons">file_download</span></a>
                        {% else %}
                        <a class="user-info-cv" href="{% url 'users:user_profile_updateCV' %}">Agregar CV&nbsp;<span class="material-icons">file_download</span></a>

                        {% endif %}
                      
                        <!-- <input type="file" class="user-info-field" readonly=true value="Preparatoria"> -->
                    </div>
                    <br>
                </div>
                
                {% if own_courses %}
                    <div class="user-current-courses-container">
                        <p class="user-info-title">Capacitaciones Impartidas</p>
                        <hr class="hr-nice">
                
                    {% include 'users/_user_own_courses_snippet.html' with courses=own_courses %}
                
                        <br>
                    </div>
                {% endif %}

                <div class="user-current-courses-container">
                    <p class="user-info-title">Capacitaciones actuales</p>
                    <hr class="hr-nice">
            
                   {% include 'users/_user_courses_snippet.html' with courses=incomplete_courses %}
            
                    <br>
                </div>
            
                <div class="user-current-courses-container">
                    <p class="user-info-title">Capacitaciones Completadas</p>
                    <hr class="hr-nice">
            
                        {% include 'users/_user_courses_snippet.html' with courses=completed_courses %}
            
                    <br>
                </div>
            </div>
        </div>

    </div>
    
</div>

{% endblock %}

src/users/templates/users/user_profilepic_form.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Social media icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- CSS -->    
    <link rel="stylesheet" href="{% static 'css/register.css' %}">

    <title>Eliminar</title>
    <link rel="icon" type="svg" href="{% static 'svg/iepam-logo-white.svg' %}">
</head>
<body>
    
    <main>
        <div class="container">
            <a class="title"><img src="{% static 'svg/iepam-logo-white.svg' %}"><p>IEPAM</p></a>
            <div class="register-container">
                <div class="register-subtitle">Actualizar Imagen</div>
                <form class="register-form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form.non_field_errors}}

                    <div class="custom-file-input">
                        {{ form.profile_pic.errors }}
                        {{ form.profile_pic }}
                    </div>

                    <div class="btn-container-vertical">
                        <button type="submit">Actualizar s</button>
                        {% if profile_view %}
                            <a class="btn-cancel" href="{% url 'users:user_profile'  %}">Cancelar</a>
                        {% else %}
                            <a class="btn-cancel" href="{% url 'users:user_detail' id=extended_user.user.pk %}">Cancelar</a>
                        {% endif %}
                    </div>
                </form>

            </div>
        </div>
    </main>
</body>
</html>