src/cursos/urls.py
from django.urls import path
from . import views

app_name = "cursos"
urlpatterns = [

    path('', views.adcourse_list_view, name='adcourse_list'),
    path('curso/crear/', views.adcourse_create_view, name='adcourse_create'),
    path('curso/editar/<int:id>/', views.adcourse_edit_view, name='adcourse_edit'),
    path('curso/<int:id>/miembros/', views.adcourse_members_view, name='adcourse_members'),
    path('curso/<int:id>/agregar-miembros/', views.adcourse_addmember_view, name='adcourse_add_members'),
    path('curso/<int:id>/agregando-miembro/<int:user_id>/', views.adcourse_addingmember_view, name='adcourse_adding_member'),
    path('curso/<int:id>/remover-miembro/<int:user_id>/', views.adcourse_members_remove_view, name='adcourse_removing_member'),
    path('curso/<int:id>/eliminar/', views.course_delete_view, name='adcourse_delete'),

    path('curso/<int:id>/add-members/', views.adcourse_addmember_view, name='adcourse_addmember'),
    path('curso/<int:id>/salir/', views.course_leave_view, name='course_quit'),


    path('menu/', views.menu, name='menu'),
    path('like/<int:id>/', views.like_curso, name='course_like'),
    path('read/<int:id>/', views.read_lecture, name='course_read_lecture'),
    path('watch/<int:id>/', views.watch_video, name='course_watch_video'),
    path('curso/<int:id>/', views.course_detail_view, name='course_detail'),

    # Modulos
    path('curso/agregar-modulo/<int:id>/', views.course_create_module_view, name='course_create_module'),
    path('curso/editar-modulo/<int:id>/', views.course_edit_module_view, name='course_edit_module'),


    path('curso/agregar-actividad/<int:id>/<int:action>/', views.course_create_item_view, name='course_create_item'),
    path('curso/editar-actividad/<int:id>/<int:action>/', views.course_edit_item_view, name='course_edit_item'),


    # Lecturas
    path('curso/lectura/<int:id>/', views.course_lecture_view, name='course_lecture'),
    path("curso/lectura/<int:id>/eliminar/", views.course_lecture_delete_view, name='course_lecture_delete'),


    # Actividades
    path('curso/actividad/<int:id>/', views.course_activity_view, name='course_activity'),
    path('curso/actividad/<int:id>/eliminar', views.course_activity_delete_view, name='course_activity_delete'),
    path('curso/entrega/<int:id>/', views.course_activity_entry_detail_view, name='course_activity_entry'),
    path('curso/entrega/<int:id>/archivo/', views.course_activity_entry_file_view, name='course_activity_entry_file'),
    path('curso/entrega/<int:id>/eliminar/', views.course_activity_entry_delete_view, name='course_activity_entry_delete'),


    # Videos
    path('curso/video/<int:id>/', views.course_video_view, name='course_video'),
    path('curso/video/<int:id>/eliminar/', views.course_video_delete_view, name='course_video_delete'),


    # Resource
    path('curso/recurso/<int:id>/', views.course_resource_view, name='course_resource'),
    path('curso/recurso/<int:id>/eliminar/', views.course_resource_delete_view, name='course_resource_delete'),
    path('curso/recurso/<int:id>/archivo/', views.course_resource_download_view, name='course_resource_file'),
    

    # Hangman
    path('curso/hangman/<int:id>/', views.course_hangman_view, name='course_hangman'),
    path('curso/hangman/<int:id>/eliminar/', views.course_hangman_delete_view, name='course_hangman_delete'),
    path('curso/hangman/<int:id>/crear-opcion/', views.course_hangman_option_create_view, name='course_hangman_add_option'),
    path('curso/hangman/<int:id>/editar-opcion/', views.course_hangman_option_edit_view, name='course_hangman_edit_option'),
    path('curso/hangman/<int:id>/eliminar-opcion/', views.course_hangman_option_delete_view, name='course_hangman_delete_option'),
    path('curso/hangman/<int:id>/play/', views.course_hangman_answer_view, name='course_hangman_play'),
    path('curso/hangman/<int:id>/complete/', views.course_hangman_complete_view, name='course_hangman_complete'),


    # Sopa
    path('curso/sopa/<int:id>/', views.course_sopa_view, name='course_sopa'),
    path('curso/sopa/<int:id>/eliminar/', views.course_sopa_delete_view, name='course_sopa_delete'),
    path('curso/sopa/<int:id>/crear-opcion/', views.course_sopa_option_create_view, name='course_sopa_add_option'),
    path('curso/sopa/<int:id>/editar-opcion/', views.course_sopa_option_edit_view, name='course_sopa_edit_option'),
    path('curso/sopa/<int:id>/eliminar-opcion/', views.course_sopa_option_delete_view, name='course_sopa_delete_option'),
    path('curso/sopa/<int:id>/play/', views.course_sopa_complete_view, name='course_sopa_complete'),

    # Puzzle
    path('curso/puzzle/<int:id>/', views.course_puzzle_view, name='course_puzzle'),
    path('curso/puzzle/<int:id>/eliminar/', views.course_puzzle_delete_view, name='course_puzzle_delete'),
    path('curso/puzzle/<int:id>/play/', views.course_puzzle_complete_view, name='course_puzzle_complete'),

    # Quiz
    path('curso/quiz/<int:id>/', views.course_quiz_view, name='course_quiz'),
    path('curso/quiz/<int:id>/eliminar/', views.course_quiz_delete_view, name='course_quiz_delete'),
    path('curso/quiz/<int:id>/answer/', views.course_quiz_answer_view, name='course_quiz_answer'),
    path('curso/quiz/<int:id>/answered/', views.course_quiz_answered_view, name='course_quiz_answered'),
    path('curso/quiz/<int:id>/submit/<int:calif>/', views.course_quiz_submit_view, name='course_quiz_submit'),
    path('curso/quiz/<int:id>/agregar-pregunta/', views.course_quiz_create_question_view, name='course_quiz_add_question'),
    path('curso/quiz/<int:id>/editar-pregunta/', views.course_quiz_update_question_view, name='course_quiz_edit_question'),
    path('curso/quiz/<int:id>/eliminar-pregunta/', views.course_quiz_delete_question_view, name='course_quiz_delete_question'),
    path('curso/quiz/<int:id>/agregar-opcion/', views.course_quiz_option_create_view, name='curso_question_add_option'),
    path('curso/quiz/<int:id>/editar-opcion/', views.course_quiz_option_update_view, name='curso_question_edit_option'),
    path('curso/quiz/<int:id>/eliminar-opcion/', views.course_quiz_option_delete_view, name='curso_question_delete_option'),
    path('curso/quiz/calificar/<int:user_pk>/<int:quiz_pk>/<int:grade>/', views.course_quiz_grade, name='curso_quiz_grade'),


]

src/iepam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('panel/', views.panel, name='panel'),
    path('cursos/', include(('cursos.urls'), namespace='cursos')),
    path('miembros/', include(('users.urls'), namespace='miembros')),

    path('my-404/',views.my404_view, name='404'),
    path('my-403/',views.my403_view, name='403'),
    path('my-500/',views.my500_view, name='500')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_DIR)

src/cursos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import Http404, FileResponse
from django.contrib.auth import get_user_model
from django.db.models import Q

import random

from .extras import side_panel_context, check_for_completion

from django.contrib.auth.decorators import login_required, permission_required

from datetime import date
from django.utils import timezone
import os

from .models import (
                        Course, Entrega, MemberOf, Modulo, 
                        Lectura, Actividad, PuzzleGame, Question, Video,
                        Quiz, QuestionOption, QuizResult,
                        FileResource, HangmanGame, HangmanOption, SopaGame,
                        SopaOption,
                    )
from .forms import (
                    CourseCreateForm, EntregaAddForm, HangmanOptionForm, LectureAddForm, 
                    ModuleAddForm, ActivityAddForm, PuzzleForm, VideoAddForm,
                    QuizForm, QuestionForm, QuestionOptionsForm, FileResourceForm,
                    HangmanForm, HangmanOption, SopaForm, SopaOptionForm,
                )

from .extras import get_iframe_url

from users.models import ExtendedUser

User = get_user_model()

# Create your views here.

template_prefix = 'cursos/'
template_admin_pre = template_prefix + 'admin/'

############################
######## Admin Views #######
############################

def adcourse_list_view(request):
    context = {}
    template_name = template_admin_pre + 'course_list.html'

    courses = Course.objects.all()
    context['courses'] = courses

    return render(request, template_name, context)

@login_required
@permission_required(['users.is_teacher'], raise_exception=True)
def adcourse_create_view(request):
    context = {}
    template_name = template_admin_pre + 'course_create_form.html'

    user = request.user
    extendedUser = user.extended_user

    course_form = CourseCreateForm()

    if request.method == 'POST':
        course_form = CourseCreateForm(request.POST, files=request.FILES)

        if course_form.is_valid():

            course = Course()

            course.name = course_form.cleaned_data['name']
            course.description = course_form.cleaned_data['description']
            course.date_created = date.today()
            course.owner = extendedUser

            if 'bg_image' in request.FILES:
                course.bg_image = request.FILES['bg_image']

            course.save()

            return redirect(reverse('cursos:course_detail', kwargs={'id': course.pk}))
        else:
            print(course_form.errors)

    context['form'] = course_form

    return render(request, template_name, context)

@login_required
def adcourse_edit_view(request, id):
    context = {}
    template_name = template_admin_pre + 'course_edit_form.html'

    course = get_object_or_404(Course, pk=id)

    if request.method == 'GET':
        course_form = CourseCreateForm(instance=course)

    if request.method == 'POST':
        course_form = CourseCreateForm(request.POST, files=request.FILES, instance=course)

        if course_form.is_valid():

            if 'bg_image' in request.FILES:
                course.bg_image = request.FILES['bg_image']

            course.save()

            return redirect(reverse('cursos:course_detail', kwargs={'id': course.pk}))
        else:
            print(course_form.errors)

    context['form'] = course_form
    context['course'] = course

    return render(request, template_name, context)


@login_required
def adcourse_members_view(request, id):
    context = {}
    template_name = template_admin_pre + 'course_members.html'

    course = get_object_or_404(Course, pk=id)

    # Get course members and non-members users
    members = MemberOf.objects.filter(course=course)
    not_members = ExtendedUser.objects.filter(~Q(courses__course=course)).exclude(Q(own_courses=course))


    if request.user.has_perm('users.is_admin'):
        if request.method == 'GET':
            username = request.GET.get('nombre')

            if username:
                not_members = not_members.filter(
                    Q(user__first_name__contains=username) |
                    Q(user__last_name__contains=username) |
                    Q(second_last_name__contains=username) 
                    # Q(user__username__contains=username)
                )

    if request.user.extended_user == course.owner:
        context['is_owner'] = True

    context['course'] = course
    context['members'] = members
    context['not_members'] = not_members

    return render(request, template_name, context)


def adcourse_members_remove_view(request, id, user_id):
    context = {}
    template_name = template_admin_pre + 'course_remove_member.html'

    course = get_object_or_404(Course, pk=id)
    user = get_object_or_404(User, pk=user_id)
    extended_user = user.extended_user

    if course.owner == extended_user:
        if request.META['HTTP_REFERER']:
            return redirect(request.META['HTTP_REFERER'])
        return redirect(reverse('cursos:adcourse_members', kwargs={'id':course.pk}))

    if MemberOf.objects.filter(course=course, member=extended_user).exists():
        if request.method == 'POST':
            membership = MemberOf.objects.filter(course=course,member=extended_user).first()
            
            read_lecture = user.read_lectures.filter(modulo__curso=course).first()
            entrega = Entrega.objects.filter(user=extended_user, actividad__modulo__curso=course).first()
            watched_video = user.watched_videos.filter(modulo__curso=course).first()
            watched_resource = user.viewed_resources.filter(modulo__curso=course).first()
            quiz_result = QuizResult.objects.filter(user=user.extended_user, quiz__modulo__curso=course).first()
            viewed_resource = user.viewed_resources.filter(modulo__curso=course).first()
            completed_hangman = user.completed_hangmans.filter(modulo__curso=course).first()
            completed_sopas = user.completed_sopas.filter(modulo__curso=course).first()
            completed_puzzle = user.completed_puzzles.filter(modulo__curso=course).first()


            if read_lecture:
                user.read_lectures.remove(read_lecture)
            if watched_video:
                user.watched_videos.remove(watched_video)
            if watched_resource:
                user.viewed_resources.remove(watched_resource)
            if viewed_resource:
                user.viewed_resources.remove(viewed_resource)
            if completed_hangman:
                user.completed_hangmans.remove(completed_hangman)
            if completed_sopas:
                user.completed_sopas.remove(completed_sopas)
            if completed_puzzle:
                user.completed_puzzles.remove(completed_puzzle)
            
            if entrega:
                entrega.delete()
            
            if quiz_result:
                quiz_result.delete()

            membership.delete()

            return redirect(reverse('cursos:adcourse_members', kwargs={'id':course.pk}))



    else:
        if request.META['HTTP_REFERER']:
            return redirect(request.META['HTTP_REFERER'])
        return redirect(reverse('cursos:adcourse_members', kwargs={'id':course.pk}))


    context['course'] = course
    context['extended_user'] = extended_user

    return render(request, template_name, context)

@login_required
def adcourse_addmember_view(request, id):
    context = {}
    template_name = template_admin_pre + 'course_add_member.html'

    course = get_object_or_404(Course, pk=id)

    members = ExtendedUser.objects.filter(~Q(courses__course=course)).exclude(Q(own_courses=course))
    # print(members)
    context['members'] = members
    context['course'] = course


    return render(request, template_name, context)


@login_required
def adcourse_addingmember_view(request, id, user_id):

    course = get_object_or_404(Course, pk=id)
    user = get_object_or_404(User, pk=user_id)
    extended_user = user.extended_user

    if course.owner == extended_user:
        if request.META['HTTP_REFERER']:
            return redirect(request.META['HTTP_REFERER'])
        return redirect(reverse('cursos:adcourse_members', kwargs={'id':course.pk}))

    try:
        membership = MemberOf(
                member=extended_user,
                course=course,
                dateJoined=date.today()
            )
        membership.save()
    except:
        print('No se pudo')
    
    # return redirect(reverse('cursos:adcourse_add_members', kwargs={'id':course.pk}))

    if request.META['HTTP_REFERER']:
        return redirect(request.META['HTTP_REFERER'])
    return redirect(reverse('cursos:adcourse_members', kwargs={'id':course.pk}))


@login_required
def adcourse_removemember_view(request, id, user_id):
    template_name = ''
    context = {}

    course = get_object_or_404(Course, pk=id)
    user = get_object_or_404(User, pk=user_id)
    extended_user = user.extended_user

    membership = get_object_or_404(MemberOf, member=extended_user, course=course)


@login_required
def adcourse_delete_view(request, id):
    context = {}
    template_name = template_admin_pre + 'course_delete.html'

    course = get_object_or_404(Course, pk=id)

    if request.method == 'POST':
        course.delete()
        return redirect(reverse('index'))

    context['course'] = course

    return render(request, template_name, context)


@login_required
def course_detail_view(request, id):
    user = request.user
    extended_user = user.extended_user
    context = {}
    template_name = template_prefix + 'course.html'

    course = get_object_or_404(Course, pk=id)
    modules = Modulo.objects.filter(curso=id)

    entregas_user = user.extended_user.entregas
    turned_activities = []
    for entrega in entregas_user.all():
        turned_activities.append(entrega.actividad)

src/cursos/templates/cursos/activity_entry.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<title>Entrega de {{ entry.user }}</title>

{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/activities.css' %}">

<div id="id-app" style="display: none;">cap</div>

<div class="container-window">

    <div class="course-container">

        <div>
            <div class="activity-header">
                <a href="{% url 'cursos:course_activity' id=activity.pk %}" class="no-style-a">
                    <div class="return">
                        <span class="material-icons">chevron_left</span>
                        Volver al entregable
                    </div>
                </a>

                {% if is_owner%}
                    <a href="{% url 'cursos:course_activity_entry_delete' id=entry.pk %}" class="button-delete no-style-a">
                        <p>Eliminar</p>
                        <span class="material-icons">delete</span>
                    </a>
                {% endif %}
            </div>

            <div class="description">{{ activity.modulo.name }}</div>

            <div class="title-smaller">Entrega de {{ entry.user }} para {{ activity.name }}</div>

            <div class="lecture-container">
                <div class="entrega-info">
                    <div style="display: inline-flex;">
                        <b>Usuario: </b>
                        <p>{{ entry.user.get_full_name }}</p>
                    </div>
                    <div style="display: inline-flex;">
                        <b>Entregada: </b>
                        <p>{{ entry.created_date }}</p>
                    </div>
                    <div style="display: inline-flex;">
                        <b>Calificación:</b>
                        <p>{% if not entry.grade %} Sin Calificar {% else %} {{ entry.grade }} {% endif %}</p>
                    </div>
                </div>

                <a class="button-edit a-button" href="{% url 'cursos:course_activity_entry_file' id=entry.pk %}">Ver Archivo<span class="material-icons">visibility</span></a>

                {% if error_message %}
                    <p>{{ error_message }}</p>
                {% endif %}

                {% if is_owner %}
                    <button class="button-edit a-button color-green" id="grade-btn">Calificar<span class="material-icons">task</span></button>

                    <form class="grade-thing" style="display: none;" method="post" id="grade-form">
                        {% csrf_token %}
                        <label for="">Calificación</label>
                        <input type="number" name="grade" id="grade">
                        <button id="cancel-btn">Cancelar</button>
                        <button type="submit">Aceptar</button>
                    </form>

                {% endif %}
            </div>

        </div>

        <div>
            {% if is_owner %}
            <div class="side-panel">
                <div class="entrega-panel">
                    <h1 style="margin-bottom: 0.5rem;">Entregas</h1>
                    {% for entrega in activity.entregas.all %}
                    <a href="{% url 'cursos:course_activity_entry' id=entrega.pk %}">
                        <div class="entrega">
                            <div class="entrega-user">{{ entrega.user }}</div>
                            <div class="entrega-date">Entregada el {{ entrega.created_date }}</div>
                        </div>
                    </a>

                            {% empty %}

                            <h4>Sin entregas</h4>

                    {% endfor %}
                </div>
            </div>
            {% else %}
            <div class="side-panel">
                {% include 'cursos/side_panel.html' %}
            </div>
            {% endif %}
        </div>

    </div>

</div>

<script>
    const gradeForm = document.getElementById('grade-form');
    const gradeBtn = document.getElementById('grade-btn');
    const cancelBtn = document.getElementById('cancel-btn');

    gradeBtn.addEventListener('click', event=>{
        event.preventDefault();
        gradeBtn.style.display = 'none';
        gradeForm.style.display = 'block'
    });

    cancelBtn.addEventListener('click', event=>{
        event.preventDefault();
        gradeBtn.style.display = 'block';
        gradeForm.style.display = 'none'
    })

</script>

{% endblock %}

src/cursos/templates/cursos/lecture.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<title> {{ lecture.name }} </title>

{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/activities.css' %}">

<div id="id-app" style="display: none;">cap</div>

<div class="container-window">

    <div class="course-container">

        <div>
            <div class="activity-header">
                <a href="{% url 'cursos:course_detail' id=lecture.modulo.curso.pk %}" class="no-style-a">
                    <div class="return">
                        <span class="material-icons">chevron_left</span>
                        Volver a la capacitación
                    </div>
                </a>
                
                {% if is_owner %}
                <a href="{% url 'cursos:course_edit_item' id=lecture.pk action=1 %}" class="button-edit no-style-a">
                    <p>Editar</p>
                    <span class="material-icons">edit</span>
                </a>
                <a href="{% url 'cursos:course_lecture_delete' id=lecture.pk %}" class="button-delete no-style-a">
                    <p>Eliminar</p>
                    <span class="material-icons">delete</span>
                </a>
                {% endif %}
            </div>

            <div class="description">{{ lecture.modulo.name }}</div>

            <div class="title">{{ lecture.name }}</div>

            <div class="description">Autor: {{ lecture.author }}</div>

            <div class="lecture-container">
                <div class="subtitle">Resumen</div>
                {{ lecture.description }}

                <div class="spaceing"></div>

                <div class="subtitle">{{ lecture.name }}</div>

                <p align="justify" style="margin-top: 0;">{{ lecture.content }}</p>

                <br>

                {% if is_member %}
                <div style="text-align: center;">
                    <a href="{% url 'cursos:course_read_lecture' id=lecture.pk %}" class="no-style-a button-view">
                        {% if viewed %}
                            <span class="material-icons">visibility_off</span>
                            Marcar como no leído
                        {% else %}
                            <span class="material-icons">visibility</span>
                            Marcar como leído
                        {% endif %}
                    </a>
                </div>
                {% endif %}

            </div>
        </div>

        <div>
            <div class="side-panel">
                {% include 'cursos/side_panel.html' %}
            </div>
        </div>

    </div>

</div>

{% endblock %}

src/cursos/templates/cursos/quiz_question_form.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Social media icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- CSS -->    
    <link rel="stylesheet" href="{% static 'css/register.css' %}">

    <title>Quiz</title>
    <link rel="icon" type="svg" href="{% static 'svg/iepam-logo-white.svg' %}">
</head>
<body>
    
    <main>
        <div class="container">
            <a class="title"><img src="{% static 'svg/iepam-logo-white.svg' %}"><p>IEPAM</p></a>
            <div class="register-container">
                <div class="register-title">Pregunta para {{ quiz.name }}</div>
                
                <form method="post" id="main-form">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    
                     <label for="">Pregunta</label>
                     <div class="input-line">
                         {{ form.prompt.errors }}
                         {{ form.prompt }}
                     </div>

                     <div id="normal-actions" style="text-align: center;">
                        <a href="{% url 'cursos:course_quiz' id=quiz.pk %}" class="btn-cancel margin-right-btn">Cancelar</a>
                        {% if editing %}
                            <button class="margin-right-btn" type="submit">Actualizar</button>
                            <button id="start-delete-btn" class="button-delete">Eliminar</button>
                        {% else %}
                            <button class="margin-left-btn margin-right-btn" type="submit">Agregar</button>
                        {% endif %}
                     </div>

                </form>

                <br>

                {% if editing %}
 
                    <label>Opciones</label>

                    {% for option in question.options.all %}
            
                        <div class="option">
                            <div style="display: grid; grid-template-columns: 1fr 0fr;">
                                <div class="option-prompt">{{ forloop.counter }}) &nbsp; {{option.prompt}}</div>
                                <span class="material-icons correct-check">{% if option.correct %}check_box{% else %}check_box_outline_blank{% endif %}</span>
                            </div>
                            <a href="{% url 'cursos:curso_question_edit_option' id=option.pk %}">Editar</a>
                            <a href="{% url 'cursos:curso_question_delete_option' id=option.pk %}">Eliminar</a>
                        </div>
            
                    {% empty %}
            
                    <h4>sin opciones</h4>
                    {% endfor %}
    
                    <a class="button-add" href="{% url 'cursos:curso_question_add_option' id=question.pk %}">Agregar opción</a>

                    <br>
                 <div class="delete-actions" id="delete-actions" style="display: none;">
                    <p>¿Estás seguro de que deseas eliminar la pregunta?</p>
                    <button class="btn-cancel" style="width: fit-content;" id="cancel-delete-btn">Cancelar</button>
                    <a class="btn-cancel margin-right-btn red-color" href="{% url 'cursos:course_quiz_delete_question' id=question.pk %}">Eliminar</a>
                </div>
                {% endif %}

            </div>
        </div>
        <script>
            const mainForm = document.getElementById('main-form');
            const deleteActions = document.getElementById('delete-actions');
            const normalActions = document.getElementById('normal-actions');
            const startdeleteBtn = document.getElementById('start-delete-btn');
            const cancelBtn = document.getElementById('cancel-delete-btn');
        
            startdeleteBtn.addEventListener('click', (event)=>{
            event.preventDefault();
            mainForm.style.display = 'none';
            deleteActions.style.display = 'block';
            normalActions.style.display = 'none';
           });
        
           cancelBtn.addEventListener('click', event=>{
               event.preventDefault();
               mainForm.style.display = 'block';
                deleteActions.style.display = 'none';
                normalActions.style.display = 'block';
           })
        </script>
    </main>
</body>
</html>

src/cursos/templates/cursos/sopa.html
{% extends 'base.html' %}

{% block head %}

{% load static %}
<title>Sopa de Letras</title>

{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/activities.css' %}">

<div id="id-app" style="display: none;">cap</div>

<div class="container-window">

    <div class="course-container">

        <div>
            <div class="activity-header">
                <a href="{% url 'cursos:course_detail' id=sopa.modulo.curso.pk %}" class="no-style-a">
                    <div class="return">
                        <span class="material-icons">chevron_left</span>
                        Volver al entregable
                    </div>
                </a>

                {% if is_owner %}
                <a href="{% url 'cursos:course_edit_item' id=sopa.pk action=7 %}" class="button-edit no-style-a">
                    <p>Editar</p>
                    <span class="material-icons">edit</span>
                </a>
                <a href="{% url 'cursos:course_sopa_delete' id=sopa.pk %}" class="button-delete no-style-a">
                    <p>Eliminar</p>
                    <span class="material-icons">delete</span>
                </a>
                {% endif %}
            </div>

            <div class="description">{{ sopa.modulo.name }}</div>

            <div class="title-smaller"> {{ sopa.title }} </div>

            <div class="lecture-container">
                <div class="subtitle">Descripción</div>
                <p>{{ sopa.description }}</p>
                {% for option in options %}
                    <div class="word-sopa">
                        <div class="word-word-sopa">
                            {{ forloop.counter }}). {{ option.option }}
                        </div>
                        <a class="word-edit" href="{% url 'cursos:course_sopa_edit_option' id=option.pk %}">Editar</a>
                        <a class="word-delete" href="{% url 'cursos:course_sopa_delete_option' id=option.pk %}">Eliminar</a>
                    </div>
                {% empty %}
                    <p>No tiene palabras</p>
                {% endfor %}
                <a class="add-word-btn" href="{% url 'cursos:course_sopa_add_option' id=sopa.pk %}">Agregar palabras</a>
            </div>

        </div>

        <div>
            <div class="side-panel">
                {% include 'cursos/side_panel.html' %}
            </div>
        </div>

    </div>

</div>

{% endblock %}